//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADMINTORNEO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Torneo
    {
        public int idTorneos { get; set; }
        public int idAdministradorITM { get; set; }
        public string TipoTorneo { get; set; }
        public string NombreTorneo { get; set; }
        public string NombreEquipo { get; set; }
        public int ValorInscripcion { get; set; }
        public System.DateTime FechaTorneo { get; set; }
        public string Integrantes { get; set; }
    
        public virtual AdministradorITM AdministradorITM { get; set; }
    }
}
